CREATE TABLE IF NOT EXISTS todo (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `title` TEXT NOT NULL,
    `description` TEXT DEFAULT NULL,
    `status` ENUM('pending', 'completed') NOT NULL DEFAULT 'pending',
    `userID` INT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(`userID`) REFERENCES user(`id`)
);
